<a href="https://colab.research.google.com/github/Hoangthang017/CS114.K21/blob/master/FaceMask_LR/FaceMask_LR_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Xây dựng model**

##**Mount drive**

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


##**Các thư viện được sử dụng trong bài**

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from imutils import paths
import os
import cv2
import numpy as np

##**Load data từ Google Drive và tiền xử lí nó**

###**Lấy đường dẫn file chưa data và khởi tạo 2 list data và label**

In [4]:
# load dataset 
print("[INFO] loading images...")
imagePaths = list(paths.list_images('/content/drive/My Drive/CS114/FaceMask/dataset'))

# khởi tạo dữ liệu
data = []

# khởi tạo label ứng với dữ liệu
labels = []

[INFO] loading images...


##**Load từng ảnh từ file và pre_process nó**

In [ ]:
# Vòng lặp để load dữ liệu 
i = 0
for imagePath in imagePaths:
	# lấy nhãn từ đường dẫn tệp
	label = imagePath.split(os.path.sep)[-2]

	# load hình ảnh ở dạng PIL(Python Imaging Library) 
	# Thay đổi kích thước ảnh đầu vào dạng 244 x 244 pixels
	image = cv2.imread(imagePath)
	
	image = cv2.resize(image,(32,32)).flatten()
	
 # đẩy dữ liệu vào data và label 
	data.append(image)
 
	if (label == "with_mask"):
			label = 1
	else:
			label = 0

	labels.append(label)
 
	i += 1

	print("done ",i)

##**Chuyển data và label sang dạng mảng**

In [8]:
# chuyển label và data sang dạng mảng 
labels = np.array(labels)
labels = labels.reshape(-1,1)
print(labels.shape)
data = np.array(data)
print(data)
print(data.shape)

(1376, 1)
[[255 255 255 ... 136 137 156]
 [  0   0   0 ...   0   0   0]
 [151 193 216 ... 159 200 223]
 ...
 [ 90 136  79 ... 124  69 250]
 [251 255 255 ... 255 255 255]
 [252 254 254 ...  63  89  93]]
(1376, 3072)


##**Chia dữ liệu thành 2 phần train và test**

In [11]:
# chia đữ liệu thành 80% để train và 20% để test
(trainX, testX, trainY, testY) = train_test_split(data, labels, test_size=0.2, stratify=labels, random_state=32)

In [12]:
print(trainX.shape)
print(trainX)

(1100, 3072)
[[251 255 255 ...  25  19  20]
 [252 250 252 ...  68  57  59]
 [  7   9  20 ... 154 163 176]
 ...
 [ 60  64  97 ... 141  56  29]
 [240 242 242 ... 225 224 226]
 [195 208 208 ... 217 208 195]]


##**Training và đánh giá model**

In [13]:
# training model 
model_Logic = LogisticRegression()
model_Logic.fit(trainX,trainY)
print(classification_report(testY, model_Logic.predict(testX)))

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


              precision    recall  f1-score   support

           0       0.96      0.93      0.95       138
           1       0.94      0.96      0.95       138

    accuracy                           0.95       276
   macro avg       0.95      0.95      0.95       276
weighted avg       0.95      0.95      0.95       276



/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


##**Save Model**

In [15]:
import pickle
f = open('/content/drive/My Drive/CS114/FaceMask/Model_LR/Model_LR.pkl', 'wb')
pickle.dump(model_Logic, f)