<a href="https://colab.research.google.com/github/Hoangthang017/CS114.K21/blob/master/FaceMask_LR/FaceMask_LR_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Xây dựng model**

##**Mount drive**

In [22]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


##**Các thư viện được sử dụng trong bài**

In [23]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from imutils import paths
import os
import cv2
import numpy as np

##**Load data từ Google Drive và tiền xử lí nó**

###**Lấy đường dẫn file chưa data và khởi tạo 2 list data và label**

In [95]:
# load dataset 
print("[INFO] loading images...")

# lấy link ảnh có khẩu trang và không có khẩu trang
imagePaths_Mask = list(paths.list_images('/content/drive/My Drive/CS114/FaceMask/FaceMask_LogicticsRegression/Datasets/Mask'))
imagePaths_No_Mask =  list(paths.list_images('/content/drive/My Drive/CS114/FaceMask/FaceMask_LogicticsRegression/Datasets/Without_mask'))

# hợp nhất 2 link vào 1 file
imagePaths = imagePaths_Mask + imagePaths_No_Mask

# khởi tạo dữ liệu
data = []

# khởi tạo label ứng với dữ liệu
labels = []

[INFO] loading images...


##**Load từng ảnh từ file và pre_process nó**

In [96]:
# Vòng lặp để load dữ liệu 

for imagePath in imagePaths:
	# lấy nhãn từ đường dẫn tệp
	label = imagePath.split(os.path.sep)[-2]

	# load hình ảnh 
	image = cv2.imread(imagePath)
	
	# preprocess ảnh
	image = cv2.resize(image,(32,32)).flatten()
	
  # đẩy dữ liệu vào data và label 
	data.append(image)
 
	# Gán label
	if (label == "Mask"):
			label = 1
	else:
			label = 0

	# đẩy label vào
	labels.append(label)

##**Chuyển data và label sang dạng mảng**

In [90]:
# chuyển label và data sang dạng mảng 
labels = np.array(labels)
labels = labels.reshape(-1,1)
data = np.array(data)

print(data)
print(data.shape)

[[ 26  35  45 ...  42  52  60]
 [  8   9  13 ...  72  96 126]
 [ 24  20  19 ... 114  91  75]
 ...
 [127 132 142 ...  64  54  77]
 [ 12  26  29 ... 120 127 170]
 [226 213 219 ...  50  57  86]]
(485, 3072)


##**Chia dữ liệu thành 2 phần train và test**

In [91]:
# chia đữ liệu thành 80% để train và 20% để test
(trainX, testX, trainY, testY) = train_test_split(data, labels, test_size=0.25, stratify=labels, random_state=1)

In [92]:
print(trainX.shape)
print(testX.shape)
print(trainX)

(363, 3072)
(122, 3072)
[[157 151 156 ...  91  92 205]
 [ 70  74  90 ...  47  69  89]
 [ 20  26  24 ...  82 134  92]
 ...
 [171 174 208 ...  13  26 197]
 [  5   1   7 ...  27   7  52]
 [ 21  39  34 ...  78  99 132]]


##**Training và đánh giá model**

In [93]:
# training model 
model_Logic = LogisticRegression()
model_Logic.fit(trainX,trainY)
print(classification_report(testY, model_Logic.predict(testX)))

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


              precision    recall  f1-score   support

           0       0.99      0.99      0.99        71
           1       0.98      0.98      0.98        51

    accuracy                           0.98       122
   macro avg       0.98      0.98      0.98       122
weighted avg       0.98      0.98      0.98       122



/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


##**Save Model**

In [94]:
import pickle
f = open('/content/drive/My Drive/CS114/FaceMask/FaceMask_LogicticsRegression/Model_LR/FaceDataset.pkl', 'wb')
pickle.dump(model_Logic, f)